# .github/workflows/release.yml
on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build_addon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT
    - name: Build
      run: hemtt release

    # Upload to Steam Workshop
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '1643238133' # Id of item to update
        contentPath: 'releases/${{ env.VERSION }}/@cfr'
        changelog: 'Content of change notes'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
